runtime: java
env: flex
runtime_config:
  jdk: openjdk11

# Define environment variables for your SQL database connection
env_variables:
  CLOUD_SQL_USERNAME: root
  CLOUD_SQL_PASSWORD: root
  CLOUD_SQL_DATABASE_NAME: wine
  CLOUD_SQL_CONNECTION_NAME: winepotent-clarity-418606:us-central1:private-instance
# Define a custom network for your application
network:
  name: projects/potent-clarity-418606/global/networks/default

# Define the Serverless VPC Access connector
vpc_access_connector:
  name: "projects/potent-clarity-418606/locations/us-central1/connectors/default-con"

handlers:
  - url: /.*
    script: this-field-is-required-but-not-used

manual_scaling:
  instances: 1




# network:
#   name: my-vpc
#   instance_ip_mode: internal
#   subnetwork_name: subnet3
#   session_affinity: true
#   # forwarded_ports:
#   #   - 8080/tcp

                      ***************************************
# runtime: java
# env: flex
# runtime_config:
#   jdk: openjdk11
# handlers:
#   - url: /.*
#     script: auto
# manual_scaling:
#   instances: 1

                    *******************************************








# network:
#   name: my-vpc
#   subnetwork_name: subnet3
#   session_affinity: true
# runtime: java
# env: flex
# runtime_config:
#   jdk: openjdk11
# handlers:
#   - url: /.*
#     script: auto
# manual_scaling:
#   instances: 1

# runtime: java
# env: flex
# runtime_config:
#   jdk: openjdk11
# handlers:
#   - url: /.*
#     script: auto
# manual_scaling:
#   instances: 1
  
# # Use the URL of your Docker image stored in Artifact Registry
# beta_settings:
#   cloud_sql_instances: # Define your Cloud SQL instance connection name if needed
#   enable_health_check: true
#   enable_stackdriver_integration: true
#   cloud_build_timeout: 1800s
#   app_start_timeout_sec: 900

# # If your application requires any services or APIs, list them under the 'service' tag
# service: default




#Working file
# runtime: java
# env: flex
# runtime_config:
#   jdk: openjdk11
# handlers:
#   - url: /.*
#     script: auto
# manual_scaling:
#   instances: 1
