
steps:
  # Step 3: Build the Maven project
  - name: 'maven:3-eclipse-temurin-11-alpine'
    entrypoint: 'mvn'
    args: ['clean', 'install']

  # Step 4: Containerize APP
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'us-central1-docker.pkg.dev/potent-clarity-418606/registry/wine-park:$SHORT_SHA', '.' ]


  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--image-url=us-central1-docker.pkg.dev/potent-clarity-418606/registry/wine-park:$SHORT_SHA']



images:
  - 'us-central1-docker.pkg.dev/potent-clarity-418606/registry/wine-park:$SHORT_SHA'


options:
  logging: CLOUD_LOGGING_ONLY
