steps:
  # Step 2: Build the Java Maven application
  - name: 'maven:3.8.4-openjdk-17'
    entrypoint: 'mvn'
    args: ['clean', 'package']
    dir: '/workspace'

  # # Step 3: Run tests (add your test command here)
  # - name: 'maven:3.8.4-openjdk-17'
  #   entrypoint: 'mvn'
  #   args: ['test']
  #   dir: '/workspace'

  # Step 4: Build the Docker image using the Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1(iowa)-docker.pkg.dev/potent-clarity-418606/registry/my-imager', '.']
    dir: '/workspace'


   - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1(iowa)-docker.pkg.dev/potent-clarity-418606/registry/my-imager']
    dir: '/workspace'
    
    #step 6: Deploy GAR image to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [ 'app', 'deploy', '--image-url', 'us-central1(iowa)-docker.pkg.dev/potent-clarity-418606/registry/my-imager' 

images:
  - 'us-central1(iowa)-docker.pkg.dev/potent-clarity-418606/registry/my-imager'

options:
  logging: CLOUD_LOGGING_ONLY
