

substitutions:
  _PROJECT_ID: potent-clarity-418606
  _REGION: us-central1
  _ARTIFACTORY_REGISTRY_REPO: wineparkapp-repo
  _IMAGE_NAME: wineparkapp-images:v2


steps:
  - name: 'gcr.io/cloud-builders/mvn'
    entrypoint: 'mvn'
    args: ['clean', 'install' , '-DskipTests']
  
 
  # Containerize APP (docker build)
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', '$_REGION-docker.pkg.dev/$_PROJECT_ID/$_ARTIFACTORY_REGISTRY_REPO/$_IMAGE_NAME', '.' ]

  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push',  '$_REGION-docker.pkg.dev/$_PROJECT_ID/$_ARTIFACTORY_REGISTRY_REPO/$_IMAGE_NAME' ]

  # Deploy GAR image to App Engine
  # - name: 'gcr.io/cloud-builders/gcloud'
  #   args: [ 'app', 'deploy', '--image-url', '$_REGION-docker.pkg.dev/$_PROJECT_ID/$_ARTIFACTORY_REGISTRY_REPO/$_IMAGE_NAME' ]

images:
  - '$_REGION-docker.pkg.dev/$_PROJECT_ID/$_ARTIFACTORY_REGISTRY_REPO/$_IMAGE_NAME'

options:
  logging: CLOUD_LOGGING_ONLY




  # steps:
  # # Build the Maven project
  # - name: 'gcr.io/cloud-builders/mvn'
  #   entrypoint: 'mvn'
  #   args: ['clean', 'install']
  #   env:
  #     - 'GOOGLE_REGION=us-central1'
 
