
#Working code 
steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - -c
      - |
        # Retrieve the region from the instance metadata server
        REGION=$(curl -H "Metadata-Flavor: Google" http://metadata.google.internal/computeMetadata/v1/instance/zone | cut -d '/' -f 4)

        # Display the region along with the log message
        echo "Region: $REGION"
     

  
 
  # Containerize APP (docker build)
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'us-central1-docker.pkg.dev/potent-clarity-418606/wineparkapp-repo/wineparkapp-images:$SHORT_SHA', '.' ]

  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push',  'us-central1-docker.pkg.dev/potent-clarity-418606/wineparkapp-repo/wineparkapp-images:$SHORT_SHA' ]

  # Deploy GAR image to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [ 'app', 'deploy', '--image-url', 'us-central1-docker.pkg.dev/potent-clarity-418606/wineparkapp-repo/wineparkapp-images:$SHORT_SHA' ]

images:
  - 'us-central1-docker.pkg.dev/potent-clarity-418606/wineparkapp-repo/wineparkapp-images:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY




  # steps:
  # # Build the Maven project
  # - name: 'gcr.io/cloud-builders/mvn'
  #   entrypoint: 'mvn'
  #   args: ['clean', 'install']
  #   env:
  #     - 'GOOGLE_REGION=us-central1'
 
