steps:
  # Step 2: Build the Java Maven application
  - name: 'maven:3-eclipse-temurin-11-alpine'
    entrypoint: 'mvn'
    args: ['clean', 'install']


  # Step 3: Run tests (add your test command here)
  # - name: 'maven:3.8.4-openjdk-17'
  #   entrypoint: 'mvn'
  #   args: ['test']
  #   dir: '/workspace'

  # Step 4: Build the Docker image using the Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/potent-clarity-418606/registry/myimage', '.']

images:
  - 'us-central1-docker.pkg.dev/potent-clarity-418606/registry/myimage'


# # Step 5: Push the Docker image to Artifact Registry
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['push', 'us-central1(iowa)-docker.pkg.dev/potent-clarity-418606/registry/myimage:$SHORT_SHA']

options:
  logging: CLOUD_LOGGING_ONLY
